"""Modells

Revision ID: 8394f29cd6ea
Revises: 
Create Date: 2021-05-25 23:59:24.235797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8394f29cd6ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    op.drop_table('user')
    op.drop_table('education')
    op.drop_table('form')
    op.drop_table('persoinfo')
    op.drop_table('social_icon')
    op.drop_table('skill')
    op.drop_table('image')
    op.drop_table('myexperience')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myexperience',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('experience_year', sa.VARCHAR(length=50), nullable=True),
    sa.Column('doneproject', sa.VARCHAR(length=50), nullable=True),
    sa.Column('happycustomers', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_rate1', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_rate2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_rate3', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_rate4', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_rate5', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_icon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_info', sa.VARCHAR(length=50), nullable=True),
    sa.Column('contact_icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('socialIcon', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persoinfo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pers_info_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pers_info_content', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('education_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('university_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('education_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('education_content', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('experience',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('company', sa.VARCHAR(length=50), nullable=True),
    sa.Column('job_date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('job_content', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
